//
//  ContinentListPresenter.swift
//  NatiaL_HW21
//
//  Created by Natia's Mac on 11.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContinentListPresentationLogic
{
  func presentSomething(response: ContinentList.Something.Response)
}

class ContinentListPresenter: ContinentListPresentationLogic
{
  weak var viewController: ContinentListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ContinentList.Something.Response)
  {
    let viewModel = ContinentList.Something.ViewModel()
   // viewController?.displaySomething(viewModel: viewModel)
  }
}
