//
//  ContinentListInteractor.swift
//  NatiaL_HW21
//
//  Created by Natia's Mac on 11.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContinentListBusinessLogic
{
  func doSomething(request: ContinentList.Something.Request)
}

protocol ContinentListDataStore
{
  //var name: String { get set }
}

class ContinentListInteractor: ContinentListBusinessLogic, ContinentListDataStore
{
  var presenter: ContinentListPresentationLogic?
  var worker: ContinentListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ContinentList.Something.Request)
  {
    worker = ContinentListWorker()
    worker?.doSomeWork()
    
    let response = ContinentList.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
